export enum Genre {
  Unknown = 'Unknown',
  Comedy = 'Comedy',
  Documentary = 'Documentary',
  Horror = 'Horror',
  Crime = 'Crime',
  Drama = 'Drama',
  Biography = 'Biography',
  Music = 'Music',
  Adventure = 'Adventure',
  Action = 'Action',
  Romance = 'Romance',
  Animation = 'Animation',
  Family = 'Family',
  ScienceFiction = 'Science Fiction',
  Fantasy = 'Fantasy',
  Thriller = 'Thriller',
}
